name: CI

on:
  push:
    branches: [ master ]

env:
  DOCKER_REGISTRY: ppaquin
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  IMAGE_NAME: recette-api

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

#      - name: Tests
#        run: |
#          cargo build --verbose
#          cargo test --verbose

      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image
        run: docker build -t ${{env.IMAGE_NAME}} .

      - name: Tag image latest
        run: docker tag ${{env.IMAGE_NAME}} ${{env.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}:latest

      - name: Tag image sha
        run: docker tag ${{env.IMAGE_NAME}} ${{env.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}:${{github.sha}}

      - name: push sha
        run: docker push ${{env.DOCKER_USERNAME}}/${{ env.IMAGE_NAME }}:${{github.sha}}

      - name: push latest
        run: docker push ${{env.DOCKER_USERNAME}}/${{ env.IMAGE_NAME }}:latest
