name: CI

on:
  push:
    branches: [ master ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  IMAGE_NAME: recette-api

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

#      - name: Tests
#        run: |
#          cargo build --verbose
#          cargo test --verbose

      - name: Build image
        run: docker build -t recette-api .

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: size=4g

#      - name: Tag image latest
#        run: docker tag recette-api ppaquin/recette-api:latest

      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: push Docker image
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ppaquin/recette-api:${{ github.sha }}
          platforms: linux/amd64,linux/arm64

#      - name: push latest
#        run: |
#          docker login
#          docker push ppaquin/recette-api:latest
