name: CI

on:
  push:
    branches: [ master ]

env:
  DOCKER_REGISTRY: ppaquin
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  IMAGE_NAME: recette-api

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

#      - name: Tests
#        run: |
#          cargo build --verbose
#          cargo test --verbose

      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build :latest
        run: docker build -t ${{env.IMAGE_NAME}}:latest .

      - name: Push to docker hub :latest
        uses: actions-hub/docker@master
        with:
          args: push ppaquin/${{env.IMAGE_NAME}}:latest
