name: CI

on:
  push:
    branches: [ master ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  IMAGE_NAME: recette-api

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

#      - name: Tests
#        run: |
#          cargo build --verbose
#          cargo test --verbose

      - name: Build image
        run: docker build -t recette-api .

      - name: Tag image latest
        run: |
          docker tag recette-api ppaquin/recette-api:latest
          docker tag recette-api ppaquin/recette-api:${{github.sha}}

      - name: Login to docker hub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          email: ${{ secrets.DOCKER_EMAIL }}
          login-path: docker-login
          config-file: './.docker/config.json'

      - name: push latest
        run: |
          docker push ppaquin/recette-api:latest
          docker push ppaquin/recette-api:${{github.sha}}
